<?php

function title_case_menu() {
    $items['title_case'] = array(
        'title' => 'Title Case Converter',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('title_case_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
        $items['title_case_success_page'] = array( //URL extension
        'title' => 'Success',
        'page callback' => 'title_case_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function title_case_form() {
    $form['user_input'] = array(
        '#title' => 'Title Case',
        '#type' => 'textfield',
        '#description' => t('Please enter the text you want to convert.'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );

    return $form;
}

function title_case_form_submit($form, &$form_state) {
  $converted_output = array();
  $user_text = $form_state['values']['user_input'];
  $user_text_all_lowercase = strtolower($user_text);
  $user_text_exploded_into_array = explode(" ", $user_text_all_lowercase);

  foreach ($user_text_exploded_into_array as $word) {
    $word[0] = strtoupper($word[0]);
    array_push($converted_output, $word);
  }
  $converted_output_imploded = implode(" ", $converted_output);
  $_SESSION['title_case_output'] = $converted_output_imploded;
  $form_state['redirect'] = 'title_case_success_page';
}


function title_case_success() {
    $output = $_SESSION['title_case_output'];
    return $output;
}
